### ISSUE TITLE
React 16 Support

### ISSUE THREAD

**Issue by didi0613** [jasonslyvia/react-menu-aim#12]
Hi,

Does `react-menu-aim` has any plans for upgrading to React 16?
Currently seeing issues: 
```
npm WARN react-menu-aim@1.0.1 requires a peer of react-dom@^0.14.0 || ^15.0.0 but none was installed
```

**Comment by jasonslyvia** [comment]
It should'd be a tough task to support React 16, all I need is time, or maybe PRs are highly welcomed too.

**Comment by didi0613** [comment]
I've create a PR here https://github.com/jasonslyvia/react-menu-aim/pull/13, welcome any code reviews

**Comment by jasonslyvia** [comment]
merged and released
