### ISSUE TITLE
Menu and menu items don't close after mouse leaves menu 

### ISSUE THREAD

**Issue by eyala-stratoscale** [jasonslyvia/react-menu-aim#8]
The menu and menu items remain open even when the mouse cursor has completely left the menu area.

**Comment by jasonslyvia** [comment]
Can you post some snippet or make a working fiddle?

**Comment by eyala-stratoscale** [comment]
You can see it in your own demo there is always a submenu open and you can't close it.
In my case I needed the menu to remain open but the submenus to close so I added a onmouseleave event for the whole div to set the active menu index to -1 and a if statement to show submenus only if the value is bigger than that.

**Comment by jasonslyvia** [comment]
I still don't see why it's relevant to `react-menu-aim`

**Comment by eyala-stratoscale** [comment]
As I see it , submenu should open when the previous menu is active or hovered, if the previous menu isn't active why should the submenu remain open ?
